# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md
#  - categories.md
#  - contacts.md



#style: light # dark or light (default)
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
