title: Kyle Zhang by @kylezgq
description: "I'm a curious kid obsessed with technology and startups."


header_pages:
  - index.md
  - about.md
  - categories.md
  - contacts.md

style: dark # dark, light (default) or hacker
listen_for_clients_preferred_style: true # false (default) or true




