title: Kyle Zhang by @kylezgq
description: "I'm a curious kid obsessed with technology and startups."
url: "https://kylezgq.github.io"

header_pages:
  - index.md
  - about.md
  - categories.md
  - contacts.md

style: dark # dark, light (default) or hacker
listen_for_clients_preferred_style: true # false (default) or true



# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
