title: 'Kyle Zhang by @kylezgq'
description: "I'm a curious kid obsessed with technology and startups."
url: "https://kylezgq.github.io"

header_pages:
  - index.md
  - about.md
  - categories.md
  - contacts.md

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
