# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - about.md
#  - categories.md
#  - contacts.md


#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
